#!/usr/bin/env node
// Fetches current pricing from LiteLLM and writes src/generated/pricing.js.
// Run as prebuild step: `node scripts/update-pricing.js`
// Falls back silently if network is unavailable — the committed stub file is used instead.

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { MODELS_TO_PRICE, FALLBACK, fetchLiteLLMData, findDeprecations } from './model-config.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '../src/generated/pricing.js');

const REPO = 'DBoocock/research-swarm';
const DEPRECATION_CHECK_WORKFLOW = 'model-deprecation-check.yml';

function perM(v) {
  // LiteLLM values are per-token — multiply by 1e6 for per-million
  return typeof v === 'number' ? v * 1e6 : 0;
}

function extractPricing(data) {
  const result = { ...FALLBACK };
  for (const { id, litellmKey } of MODELS_TO_PRICE) {
    const entry = data[litellmKey];
    if (!entry) continue;
    result[id] = {
      inp: perM(entry.input_cost_per_token),
      out: perM(entry.output_cost_per_token),
      cw:  perM(entry.cache_creation_input_token_cost ?? 0),
      cr:  perM(entry.cache_read_input_token_cost    ?? 0),
    };
  }
  return result;
}

function warnDeprecations(data) {
  const findings = findDeprecations(data);
  if (!findings.length) return;
  console.warn('\nupdate-pricing: model deprecation warning(s):');
  for (const f of findings) {
    const when = f.daysUntil < 0 ? `${-f.daysUntil} days ago` : `in ${f.daysUntil} days`;
    console.warn(`  - ${f.id} (${f.litellmKey}): deprecates ${f.deprecationDate} (${when})${f.source ? ` — ${f.source}` : ''}`);
  }
  console.warn('  See scripts/check-model-deprecation.js / the monthly model-deprecation-check workflow for tracking.\n');
}

// Non-fatal: warns if the scheduled deprecation-check workflow has been
// disabled (GitHub auto-disables scheduled workflows after 60 days with no
// repository activity) — the one failure mode that check can't detect on
// its own, since a disabled workflow never runs to report anything.
async function warnIfDeprecationCheckDisabled() {
  try {
    const headers = { Accept: 'application/vnd.github+json' };
    if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
    const res = await fetch(
      `https://api.github.com/repos/${REPO}/actions/workflows/${DEPRECATION_CHECK_WORKFLOW}`,
      { headers, signal: AbortSignal.timeout(8000) }
    );
    if (!res.ok) return; // workflow not found yet, rate-limited, etc. — not worth failing the build over
    const workflow = await res.json();
    if (workflow.state !== 'active') {
      console.warn(`\nupdate-pricing: the ${DEPRECATION_CHECK_WORKFLOW} scheduled workflow is "${workflow.state}", not active.`);
      console.warn('  GitHub disables scheduled workflows after 60 days with no repository activity —');
      console.warn('  re-enable it from the Actions tab if this is unexpected.\n');
    }
  } catch {
    // Network hiccup or offline build — same "don't fail the build" policy as the pricing fetch itself.
  }
}

async function main() {
  let pricing = FALLBACK;
  try {
    const data = await fetchLiteLLMData();
    pricing = extractPricing(data);
    console.log('update-pricing: fetched live pricing from LiteLLM');
    warnDeprecations(data);
  } catch (e) {
    console.warn('update-pricing: using fallback pricing (' + e.message + ')');
  }

  await warnIfDeprecationCheckDisabled();

  mkdirSync(join(__dirname, '../src/generated'), { recursive: true });
  const lines = Object.entries(pricing).map(
    ([id, p]) => `  ${JSON.stringify(id)}: { inp: ${p.inp}, out: ${p.out}, cw: ${p.cw}, cr: ${p.cr} },`
  );
  writeFileSync(OUT,
    '// Auto-generated by scripts/update-pricing.js — do not edit by hand\n' +
    'export const PRICING = {\n' +
    lines.join('\n') +
    '\n};\n'
  );
  console.log('update-pricing: wrote ' + OUT);
}

main().catch(e => { console.error(e); process.exit(1); });
