#!/usr/bin/env node
// Fetches current pricing from LiteLLM and writes src/generated/pricing.js.
// Run as prebuild step: `node scripts/update-pricing.js`
// Falls back silently if network is unavailable — the committed stub file is used instead.

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '../src/generated/pricing.js');

// Models we price. Every ID here must be the EXACT string modelFor() in
// src/models.js can return — these strings are used as both the LiteLLM
// lookup key and the PRICING storage key, so priceFor() finds them with a
// plain object lookup. LiteLLM publishes bare (non-prefixed) entries for
// Gemini/DeepSeek with identical pricing to their provider-prefixed
// counterparts, so no separate mapping is needed. Keep this list in sync
// with src/models.js's MODELS table and SYNTHESIS_TIER premium mappings —
// see tests/pricing-keys.spec.js, which fails if they drift apart.
const MODELS_TO_PRICE = [
  'claude-sonnet-4-6',
  'claude-opus-4-8',
  'claude-haiku-4-5-20251001',
  'gemini-2.5-flash',
  'gemini-2.5-flash-lite',
  'deepseek-v4-flash',
  'deepseek-v4-pro',
  'gpt-4.1',
  'gpt-4.1-mini',
  'o3',
];

// Fallback pricing (per-million-token, in USD) used when LiteLLM is unreachable
const FALLBACK = {
  'claude-sonnet-4-6':                   { inp: 3.00, out: 15.00, cw: 3.75, cr: 0.30 },
  'claude-opus-4-8':                     { inp: 5.00, out: 25.00, cw: 6.25, cr: 0.50 },
  'claude-haiku-4-5-20251001':           { inp: 1.00, out: 5.00, cw: 1.25, cr: 0.10 },
  'gemini-2.5-flash':                    { inp: 0.30, out: 2.50, cw: 0, cr: 0.03 },
  'gemini-2.5-flash-lite': { inp: 0.10, out: 0.40, cw: 0, cr: 0.01 },
  'deepseek-v4-flash':                   { inp: 0.14, out: 0.28, cw: 0, cr: 0.0028 },
  'deepseek-v4-pro':                     { inp: 0.435, out: 0.87, cw: 0, cr: 0.003625 },
  'gpt-4.1':                             { inp: 2.00, out: 8.00, cw: 0, cr: 0.50 },
  'gpt-4.1-mini':                        { inp: 0.40, out: 1.60, cw: 0, cr: 0.10 },
  'o3':                                  { inp: 2.00, out: 8.00, cw: 0, cr: 0.50 },
};

async function fetchPricing() {
  const url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
  const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

function perM(v) {
  // LiteLLM values are per-token — multiply by 1e6 for per-million
  return typeof v === 'number' ? v * 1e6 : 0;
}

function extractPricing(data) {
  const result = { ...FALLBACK };
  for (const model of MODELS_TO_PRICE) {
    const entry = data[model];
    if (!entry) continue;
    result[model] = {
      inp: perM(entry.input_cost_per_token),
      out: perM(entry.output_cost_per_token),
      cw:  perM(entry.cache_creation_input_token_cost ?? 0),
      cr:  perM(entry.cache_read_input_token_cost    ?? 0),
    };
  }
  return result;
}

async function main() {
  let pricing = FALLBACK;
  try {
    const data = await fetchPricing();
    pricing = extractPricing(data);
    console.log('update-pricing: fetched live pricing from LiteLLM');
  } catch (e) {
    console.warn('update-pricing: using fallback pricing (' + e.message + ')');
  }

  mkdirSync(join(__dirname, '../src/generated'), { recursive: true });
  const lines = Object.entries(pricing).map(
    ([id, p]) => `  ${JSON.stringify(id)}: { inp: ${p.inp}, out: ${p.out}, cw: ${p.cw}, cr: ${p.cr} },`
  );
  writeFileSync(OUT,
    '// Auto-generated by scripts/update-pricing.js — do not edit by hand\n' +
    'export const PRICING = {\n' +
    lines.join('\n') +
    '\n};\n'
  );
  console.log('update-pricing: wrote ' + OUT);
}

main().catch(e => { console.error(e); process.exit(1); });
