#!/usr/bin/env node
// Fetches current pricing from LiteLLM and writes src/generated/pricing.js.
// Run as prebuild step: `node scripts/update-pricing.js`
// Falls back silently if network is unavailable — the committed stub file is used instead.

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '../src/generated/pricing.js');

// Models we price, keyed by model ID used in src/models.js
const MODELS_TO_PRICE = [
  'claude-sonnet-4-6',
  'claude-opus-4-8',
  'claude-haiku-4-5-20251001',
  'gemini/gemini-2.5-flash',
  'gemini/gemini-2.5-flash-lite-preview-06-17',
  'gemini/gemini-2.5-pro',
  'deepseek/deepseek-v4-flash',
  'deepseek/deepseek-v4',
  'gpt-4.1',
  'gpt-4.1-mini',
];

// Fallback pricing (per-million-token, in USD) used when LiteLLM is unreachable
const FALLBACK = {
  'claude-sonnet-4-6':                      { inp: 3.00, out: 15.00, cw: 3.75, cr: 0.30 },
  'claude-opus-4-8':                        { inp: 15.00, out: 75.00, cw: 18.75, cr: 1.50 },
  'claude-haiku-4-5-20251001':              { inp: 0.80, out: 4.00, cw: 1.00, cr: 0.08 },
  'gemini/gemini-2.5-flash':               { inp: 0.15, out: 0.60, cw: 0, cr: 0 },
  'gemini/gemini-2.5-flash-lite-preview-06-17': { inp: 0.075, out: 0.30, cw: 0, cr: 0 },
  'gemini/gemini-2.5-pro':                 { inp: 1.25, out: 10.00, cw: 0, cr: 0 },
  'deepseek/deepseek-v4-flash':            { inp: 0.27, out: 1.10, cw: 0, cr: 0 },
  'deepseek/deepseek-v4':                  { inp: 0.27, out: 1.10, cw: 0, cr: 0 },
  'gpt-4.1':                               { inp: 2.00, out: 8.00, cw: 0, cr: 0 },
  'gpt-4.1-mini':                          { inp: 0.40, out: 1.60, cw: 0, cr: 0 },
};

async function fetchPricing() {
  const url = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
  const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

function perM(v) {
  // LiteLLM values are per-token — multiply by 1e6 for per-million
  return typeof v === 'number' ? v * 1e6 : 0;
}

function extractPricing(data) {
  const result = { ...FALLBACK };
  for (const model of MODELS_TO_PRICE) {
    const entry = data[model];
    if (!entry) continue;
    result[model] = {
      inp: perM(entry.input_cost_per_token),
      out: perM(entry.output_cost_per_token),
      cw:  perM(entry.cache_creation_input_token_cost ?? 0),
      cr:  perM(entry.cache_read_input_token_cost    ?? 0),
    };
  }
  return result;
}

async function main() {
  let pricing = FALLBACK;
  try {
    const data = await fetchPricing();
    pricing = extractPricing(data);
    console.log('update-pricing: fetched live pricing from LiteLLM');
  } catch (e) {
    console.warn('update-pricing: using fallback pricing (' + e.message + ')');
  }

  mkdirSync(join(__dirname, '../src/generated'), { recursive: true });
  const lines = Object.entries(pricing).map(
    ([id, p]) => `  ${JSON.stringify(id)}: { inp: ${p.inp}, out: ${p.out}, cw: ${p.cw}, cr: ${p.cr} },`
  );
  writeFileSync(OUT,
    '// Auto-generated by scripts/update-pricing.js — do not edit by hand\n' +
    'export const PRICING = {\n' +
    lines.join('\n') +
    '\n};\n'
  );
  console.log('update-pricing: wrote ' + OUT);
}

main().catch(e => { console.error(e); process.exit(1); });
